preferences:
  general:
    audioLib: SoundDevice
    units: deg

window:
  size: [1440, 900]
  pos: [0, 0]
  color: [0, 0, 0]
  fullscr: True
  #winType: pyglet
  waitBlanking: True
  screen: 0

monitor:
  name: default
  width: 36.3  # in cm
  distance: 50  # in cm
  gamma: 1.

mouse:
  visible: False

eyetracker:
  model: eyelink
  CNUM: 9
  MIN_CALIB_FIX: 1000

mri:
  simulate: False
  TR: 2.0  # seconds between volume acquisitions
  TA: 2.0  # seconds to acquire one volume
  volumes: 10  # number of 3D volumes to obtain in a given scanning run
  sync: t  # character used as flag for sync timing, default=‘5’
  skip: 0  # how many frames to silently omit initially during T1 stabilization, no sync pulse.
  sound: False  # simulate scanner noise

flicker_experiment:
  frequencies: [.5, 1, 2, 4, 8, 16, 0, 0, 0, 0, 16, 8, 4, 2, 1, .5, 0, 0, 0, 0]
  durations: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
  repeats: 4

  #durations: [30]
  #frequencies: [1]
  size: 15
  fixation_size_prop: .05
  mean_color_duration: 2
  position: [0, 0]
  keys: [z, x, n, m]
